name: Docker Build, Push and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: felixlutze/d1-friseur-web:${{ github.run_id }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: pip install ansible

      - name: Add Infrastructure hosts
        run: cd ansible && echo [infrastructure] > inventory.txt && ${{ secrets.HOSTS_INFRASTRUCTURE }} >> inventory.txt && cat inventory.txt

      - name: Deploy Docker image using Ansible
        run: cd ansible && ansible-playbook -i inventory.txt deploy_docker_image.yml -e "docker_image_tag=${{ github.run_id }}"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_INFRASTRUCTURE }}
